### ISSUE TITLE
Create use case diagram

### ISSUE THREAD

**Issue by kadamQ** [TeljesenMindegy/afp2-harmas-csapat#1]
Create use case diagram, which contains the following:
- [x] Identify actors
- [x] Identify use cases
- [x] Indicate relationships

**Comment by eperatis** [comment]
I identified actors and make the usecase.
Check here:
[documents](https://github.com/TeljesenMindegy/afp2-harmas-csapat/blob/master/documentation/README.md)

**Comment by TeljesenMindegy** [comment]
Added an alternative use case diagram completed with relationships. [Here](https://github.com/TeljesenMindegy/afp2-harmas-csapat/blob/master/documentation/useCaseDiagram.md#pizzeria-use-case-uml-diagram)

**Comment by kadamQ** [comment]
First of all, I appreciate both of @eperatis's work and @TeljesenMindegy's work, but I found @TeljesenMindegy's UML diagram more detailed and more complex.
Although I found some mistakes too, nothing serious, you just misspelled "Scheduling algorithm optimize preparation" at the bottom of the diagram, you wrote "sceduling". And one more: At the lower right corner, you should not use a line with the arrowhead between "Carry delivery" use case and the "Delivery guy" actor. It should be a simple line because it looks inconsistent compared with the other same lines.

**Comment by TeljesenMindegy** [comment]
Thanks for the feedback, I fixed the mentioned problems.
